name: CI

on:
    pull_request:
        branches:
            - "**"

jobs:
    build-sc:
        uses: ./.github/workflows/build-smart-contracts.yml
        secrets:
            HARDHAT_FORKING_URL: ${{ secrets.HARDHAT_FORKING_URL }}
